spring:
  data:
    mongodb:
      host: 23.99.127.85
      port: 27017      # Specify the port MongoDB is running on
      database: billing_reports

#server:
#  port: 8081


#OpenAPI Properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
